server:
  port: 8082
  error:
    include-message: always
    include-stacktrace: never

spring:
  application:
    name: OmniChannelEmail
  config:
    activate:
      on-profile: dev
    import: optional:configserver:http://oc-config
  cloud:
    compatibility-verifier:
      enabled: false

EUREKA_HOST: eurekahost
EUREKA_PORT: 80

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka
      instance:
      preferIpAddress: true
  instance:
    hostname: ${spring.cloud.client.ip-address}
    ip-address: ${spring.cloud.client.ip-address}

springdoc:
  swagger-ui:
    defaultModelsExpandDepth: -1
