CREATE TABLE email_template (
ID int NOT NULL AUTO_INCREMENT,
NAME varchar(50) DEFAULT NULL,
SUBJECT varchar(50) DEFAULT NULL,
FILE_PATH varchar(255) DEFAULT NULL,
MODE varchar(50) DEFAULT NULL,
ACTIVE tinyint(1) DEFAULT '0',
CREATED_BY varchar(50) DEFAULT NULL,
CREATED_ON timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (ID)
);