CREATE TABLE email_history (
ID int NOT NULL AUTO_INCREMENT,
USER_ID varchar(50) NOT NULL,
MEMBER_ID varchar(50) NOT NULL,
FROM_EMAIL varchar(50) NOT NULL,
TO_EMAIL varchar(50) NOT NULL,
EMAIL_SUBJECT varchar(100) DEFAULT NULL,
BODY longtext,
CREATED_BY varchar(255) DEFAULT NULL,
CREATED_ON timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (ID)
);