CREATE TABLE `email_audit` (
`ID` int NOT NULL AUTO_INCREMENT,
`CARE_MANAGER` varchar(100) DEFAULT NULL,
`NOTE` varchar(100) DEFAULT NULL,
`CREATED_ON` timestamp NULL DEFAULT NULL,
`DISTRIBUTION_LIST` varchar(50) DEFAULT NULL,
`TEMPLATE` varchar(50) DEFAULT NULL,
`STATUS` varchar(255) DEFAULT NULL,
`REASON` varchar(255) DEFAULT NULL,
`MODE` varchar(50) DEFAULT NULL,
PRIMARY KEY (`ID`)
); 