ALTER TABLE user_master drop COLUMN PHONENUMBER,drop COLUMN EMAIL_ID,drop COLUMN FIRST_NAME,drop COLUMN MIDDLE_NAME,drop COLUMN LAST_NAME;

ALTER TABLE user_master ADD COLUMN FIRST_NAME VARCHAR(100) AFTER USER_ID, ADD COLUMN MIDDLE_NAME VARCHAR(100) AFTER FIRST_NAME, ADD COLUMN LAST_NAME VARCHAR(100) AFTER MIDDLE_NAME ;

ALTER TABLE user_master ADD COLUMN PHONE_NUMBER VARCHAR(100) after LAST_NAME,ADD COLUMN EMAIL_ID VARCHAR(100) after PHONE_NUMBER ;