ALTER TABLE user_master ADD COLUMN FIRST_NAME VARCHAR(100) AFTER USER_ID, ADD COLUMN MIDDLE_NAME VARCHAR(100) AFTER FIRST_NAME, ADD COLUMN LAST_NAME VARCHAR(100) AFTER MIDDLE_NAME ;

ALTER TABLE member_care_manager_mapping ADD COLUMN CARE_MANAGER_FULL_NAME VARCHAR(255) AFTER CARE_MANAGER, ADD COLUMN MEMBER_FULL_NAME VARCHAR(255) AFTER MEMBER;

ALTER TABLE sms_conversation ADD COLUMN SENDER_FULL_NAME VARCHAR(255) AFTER USER_ID, ADD COLUMN RECEIVER_FULL_NAME VARCHAR(255) AFTER MEMBER_ID;