server:
  port: 8090
  error:
    include-message: always
    include-stacktrace: never


spring:
  config:
    activate:
      on-profile: dev
    import: optional:configserver:http://oc-config
  application:
    name: omni-apigateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: foos
          uri: http://localhost:8090
          predicates:
            - Path=/foos/**
  main:
    web-environment: false

EUREKA_HOST: eurekahost
EUREKA_PORT: 80


eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka
      instance:
      preferIpAddress: true
  instance:
    hostname: ${spring.cloud.client.ip-address}
    ip-address: ${spring.cloud.client.ip-address}

omnichannel:
  singleSmsUrl: https://oc-dev.zyterk8s.net
  campaignUrl: https://oc-dev-campaign.zyterk8s.net/campaign
  webOrigins: oc-auth.zyterk8s.net,oc-dev.zyterk8s.net,oc-dev-campaign.zyterk8s.net

realm: https://oc-auth.zyterk8s.net/auth/realms/zyter