spring:
  cloud:
    config:
      server:
        git:
          uri: "https://zyteradmin@bitbucket.org/zyteradmin/omnichannel-config.git"
          username: ${git.config.username}
          password: ${git.config.password}

server:
  port: 8888